// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyect.Models;

namespace Proyect.Migrations
{
    [DbContext(typeof(DbaContext))]
    [Migration("20190710185034_ProyectDB")]
    partial class ProyectDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyect.Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Direccion");

                    b.Property<string>("Nombres");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyect.Models.Factura", b =>
                {
                    b.Property<string>("FacturaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClienteId");

                    b.Property<DateTime>("Fecha");

                    b.Property<double>("TotalCompra");

                    b.HasKey("FacturaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Proyect.Models.FacturaDetalle", b =>
                {
                    b.Property<string>("FacturaDetalleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClienteId");

                    b.Property<string>("FacturaId");

                    b.Property<double>("Precio");

                    b.Property<string>("ProductoId");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("Proyect.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<string>("Marca");

                    b.Property<double>("PrecioCompra");

                    b.Property<double>("PrecioVenta");

                    b.Property<string>("Size");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyect.Models.Factura", b =>
                {
                    b.HasOne("Proyect.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("Proyect.Models.FacturaDetalle", b =>
                {
                    b.HasOne("Proyect.Models.Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId");

                    b.HasOne("Proyect.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");
                });
#pragma warning restore 612, 618
        }
    }
}
